Refactored a bunch of code. The repl and command line script that wraps it now seems to work reasonably well although I'm still not completely happy with it.
There is also an outstanding problem with the ENV overwrites for the
database settings. What I expected to work as defaults did not
for whatever reason. Therefore these settings cannot currently
be overwritten by environment variables. I'm thinking moving forward
it might be worth explicitly wrapping the repl using java code and a
proper command line options parser.

diff --git a/src/resources/victims b/src/resources/victims
--- a/src/resources/victims
+++ b/src/resources/victims
@@ -3,18 +3,19 @@
 # Convenience Wrapper for the victims cli 
 ###############################################################################
 
-# default settings
-VICTIMS_SERVICE_URI="http://www.victi.ms"
-VICTIMS_SERVICE_ENTRY="service/"
-VICTIMS_ENCODING="UTF-8"
-VICTIMS_HOME="${HOME}/.victims"
-VICTIMS_CACHE_PURGE="false"
-VICTIMS_ALGORITHMS="MD5,SHA1,SHA512"
-VICTIMS_DB_DRIVER="org.h2.Driver"
-VICTIMS_DB_URL="jdbc:${VICTIMS_HOME}/victims;MVCC=true"
-VICTIMS_DB_USER="victims"
-VICTIMS_DB_PASS="victims"
-VICTIMS_DB_PURGE="false"
+# victims client configuration. 
+# use environment variables to overwrite defaults.
+VICTIMS_SERVICE_URI=${VICTIMS_SERVICE_URI:-"http://www.victi.ms"}
+VICTIMS_SERVICE_ENTRY=${VICTIMS_SERVICE_ENTRY:-"service/"}
+VICTIMS_ENCODING=${VICTIMS_ENCODING:-"UTF-8"}
+VICTIMS_HOME=${VICTIMS_HOME:-"${HOME}/.victims"}
+VICTIMS_CACHE_PURGE=${VICTIMS_CACHE_PURGE:-"false"}
+VICTIMS_ALGORITHMS=${VICTIMS_ALGORITHMS:-"MD5,SHA1,SHA512"}
+VICTIMS_DB_DRIVER=${VICTIMS_DB_DRIVER:-"org.h2.Driver"}
+#VICTIMS_DB_URL=${VICTIMS_DB_URL:-"jdbc:/tmp/victims.db;MVCC=true"}
+#VICTIMS_DB_USER=${VICTIMS_DB_USER:-"victims"}
+#VICTIMS_DB_PASS=${VICTIMS_DB_PASS:-"victims"}
+VICTIMS_DB_PURGE=${VICTIMS_DB_PURGE:-"false"}
 
 # victims client version 
 VICTIMS_CLIENT_VERSION="1.0-SNAPSHOT"
@@ -22,8 +23,11 @@ VICTIMS_CLIENT_VERSION="1.0-SNAPSHOT"
 # standalone jar file
 VICTIMS_JAR="victims-client-${VICTIMS_CLIENT_VERSION}-standalone.jar"
 
+# client .jar file
+VICTIMS_CLIENT="${VICTIMS_HOME}/bin/${VICTIMS_JAR}"
+
 # base command
-VICTIMS_CMD="java -jar ${VICTIMS_HOME}/bin/${VICTIMS_JAR}"
+VICTIMS_CMD="java -jar ${VICTIMS_CLIENT}"
 
 debug_env(){
     echo "VICTIMS_CLIENT_VERSION = ${VICTIMS_CLIENT_VERSION}"
@@ -35,74 +39,143 @@ debug_env(){
     echo "VICTIMS_HOME = ${VICTIMS_HOME}"
     echo "VICTIMS_CACHE_PURGE = ${VICTIMS_CACHE_PURGE}"
     echo "VICTIMS_ALGORITHMS = ${VICTIMS_ALGORITHMS}"
-    echo "VICTIMS_DB_DRIVER = ${VICTIMS_DB_DRIVER}"
-    echo "VICTIMS_DB_URL = ${VICTIMS_DB_URL}"
-    echo "VICTIMS_DB_USER = ${VICTIMS_DB_USER}"
-    echo "VICTIMS_DB_PASS = ${VICTIMS_DB_PASS}"
+#    echo "VICTIMS_DB_DRIVER = ${VICTIMS_DB_DRIVER}"
+#    echo "VICTIMS_DB_URL = ${VICTIMS_DB_URL}"
+#    echo "VICTIMS_DB_USER = ${VICTIMS_DB_USER}"
+#    echo "VICTIMS_DB_PASS = ${VICTIMS_DB_PASS}"
     echo "VICTIMS_DB_PURGE = ${VICTIMS_DB_PURGE}"
+}
+
+require_env(){
+    if [ "${1}X" == "X" ]; then
+        echo "error: $2"
+        exit 1
+    fi
+}
+
+require_path(){
+    if [ ! -e "${1}" ]; then
+        echo "error: required path '${1}' not found"
+        exit 1
+    fi
 }
 
 # ensure that everything is setup correctly 
 checkenv(){
-    jvm=which java
-    if [ -n "${jvm+x}" ]; then
-        echo "Java is required to run victims client"
-        exit 1
-    fi
-    
-    if [ -n "${VICTIMS_HOME+x}" ]; then 
-        echo "VICTIMS_HOME environment variable not set"
-        exit 1
-    fi
-
-    if [ ! -e "${VICTIMS_HOME}/${VICTIMS_JAR}" ]; then
-        echo "${VICTIMS_HOME}/${VICTIMS_JAR} not found"
-        exit 1
-    fi
+    require_env $(which java)     "Java is required to run victims client"
+    require_env ${VICTIMS_HOME}   "VICTIMS_HOME environment variable not set"
+    require_path "${VICTIMS_CLIENT}" 
 }
 
-#scan(){
-#    runner "scan" "$@"
-#}
 
-#update(){
-#    last_update="$(${VICTIMS_CMD} last-update)"
-#    if [ -n "${last_update+x}" ]; then
-#        last_update="1970-01-01T00:00:00" 
-#    fi
-#    echo "Checking for updates. Last updated ${last_update}"
-#    runner "sync"
-#}
+last_updated(){
+    last_update="$(${VICTIMS_CMD} last-update)"
+    echo "Vulnerability definitions last updated: ${last_update}."
+}
 
 runner(){
+
+# TODO: Database configuration settings = broken..
+#config set victims.db.driver "${VICTIMS_DB_DRIVER}"
+#config set victims.db.url "${VICTIMS_DB_URL}"
+#config set victims.db.user "${VICTIMS_DB_USER}"
+#config set victims.db.pass "${VICTIMS_DB_PASS}"
+
     ${VICTIMS_CMD} <<EOF
+quiet
 config set victims.service.uri "${VICTIMS_SERVICE_URI}"
 config set victims.service.entry "${VICTIMS_SERVICE_ENTRY}"
 config set victims.encoding "${VICTIMS_ENCODING}"
 config set victims.home "${VICTIMS_HOME}"
 config set victims.cache.purge "${VICTIMS_CACHE_PURGE}"
 config set victims.algorithms "${VICTIMS_ALGORITHMS}"
-config set victims.db.driver "${VICTIMS_DRIVER}"
-config set victims.db.url "${VICTIMS_DB_URL}"
-config set victims.db.user "${VICTIMS_DB_USER}"
-config set victims.db.pass "${VICTIMS_DB_PASS}"
 config set victims.db.purge "${VICTIMS_DB_PURGE}"
 $@
 EOF
-
+    if [ $? != 0 ]; then
+        "error: victims command failed - $@"
+    fi
 }
 
 usage(){
-    echo "warning - Use at your own risk"
+    cat <<USAGE
+
+victims - Check jar files against a database of known vulnerable 
+          artifacts. 
+
+Usage:
+
+    -h          Shows this help message.
+
+    -u          Updates the victims vulnerability definitions.
+
+    -s  <path>  Scans the supplied file or directory to see if 
+                it matches a definition in the victims vulnerability
+                database.
+
+    -i          Interactive mode.
+
+Examples:
+
+  To update the victims vulnerability definitions - 
+    victims -u 
+
+  To scan a jar file for vulnerabilities: 
+    victims -s example.jar 
+
+
+For more detailed configuration options please refer to the victims man page. 
+
+USAGE
+
 }
 
 main(){
+
     if [ -n "${VICTIMS_DEBUG+x}" ]; then 
         debug_env
     fi
-    # TODO Use getopt to accept multiple command line options
-    # e.g. ./victims --sync --home=/tmp/victims *.jar
-    runner "$@"
+
+    if [ $# -eq 0 ]; then
+        usage
+        exit 1
+    fi
+
+    checkenv
+    last_updated
+
+    while getopts ":hus:i" opt; do
+        case $opt in
+            h)
+                usage
+                exit 1
+                ;;
+            \?)
+                echo "Invalid option: -$OPTARG"
+                usage
+                exit 1
+                ;;
+            :)
+                echo "Option -$OPTARG requires an argument"
+                usage
+                exit 1
+                ;;
+            u)
+                echo "Synchronizing with the database. Please wait.."
+                runner "sync" 
+                ;;
+
+            i)  echo "Entering interactive mode" 
+                ${VICTIMS_CMD}
+                ;;
+
+            s)
+                echo "Scanning ${OPTARG}.."
+                runner "scan" "$OPTARG" 
+                ;;
+        esac
+    done
+    exit $?
 }
 
 main "$@"
